---
title: Miguel Carvajal
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: mcarvajal@umh.es
tagline: Profesor de Periodismo
baseurl: ''
url: http://miguelcarvajal.es
future: true
authors: Miguel Carvajal
markdown: kramdown
include:
- _pages
permalink: "/:title/"
sass:
  sass_dir: _sass
  style: compressed
host: localhost
plugins:
- jekyll-feed
- jekyll-paginate
- jekyll-redirect-from
- jekyll-seo-tag
- jekyll-sitemap
exclude:
- ".sass-cache"
- ".netlify"
- vendor/
- Gemfile
- Gemfile.lock
- README.md
