---
title: Miguel Carvajal
description: Profesor de Periodismo y director del Máster en Innovación en Periodismo de la Universidad Miguel Hernández
url: http://miguelcarvajal.es
email: mcarvajal@umh.es
tagline: Profesor de Periodismo

future: true

author: Miguel Carvajal
twitter: 
  username: mcarvajal_
  card: summary
social:
  name: Miguel Carvajal
  links:
    - https://twitter.com/mcarvajal_
    - https://www.facebook.com/miguelcarvajal
    - https://github.com/miguelcarvajal

timezone: ES
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true

markdown: kramdown

include:
- _pages
permalink: /:categories/:year/:month/:day/:title:output_ext

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Compression
sass:
  sass_dir: _sass
  style: compressed

# Host
host: localhost

# Plugins 
plugins:
- jekyll-feed
- jekyll-paginate
- jekyll-redirect-from
- jekyll-seo-tag
- jekyll-sitemap

exclude:
- ".sass-cache"
- ".netlify"
- vendor/
- Gemfile
- Gemfile.lock
- README.md

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"