# Dependencies
markdown:         redcarpet
highlighter:      pygments

redcarpet:
    extensions: 
      - no_intra_emphasis
      - fenced_code_blocks
      - tables
      - strikethrough
      - superscript
      - autolink
      - hard_wrap
      - footnotes

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Miguel Carvajal
tagline:          'Notas, enlaces y reflexiones sobre periodismo'
description:      'Profesor en la <a href="http://periodismo.umh.es" target="_blank">UMH</a> y director del Máster en Innovación en Periodismo <a href="http://mip.umh.es" target="_blank">(MIP)</a>.'
url:              http://miguelcarvajal.es

author:
  name:           'Miguel Carvajal'
  url:            https://twitter.com/sintomatico

paginate:        5

# Custom vars
version:          2.1.0

github:
  repo:           miguelcarvajal/miguelcarvajal.github.com
  branch:         master