---
title: Miguel Carvajal
description: P치gina web de Miguel Carvajal, profesor de Periodismo y director del M치ster en Innovaci칩n en Periodismo de la Universidad Miguel Hern치ndez
url: http://miguelcarvajal.es
author: Miguel Carvajal
twitter: 
  username: mcarvajal_
  card: summary
social:
  name: Miguel Carvajal
  links:
    - https://twitter.com/mcarvajal_
    - https://www.facebook.com/miguelcarvajal
    - https://github.com/miguelcarvajal

timezone: ES
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: mcarvajal@umh.es
tagline: Profesor de Periodismo
baseurl: ''
future: true
markdown: kramdown
include:
- _pages
permalink: /:categories/:year/:month/:day/:title:output_ext
sass:
  sass_dir: _sass
  style: compressed
host: localhost
plugins:
- jekyll-feed
- jekyll-paginate
- jekyll-redirect-from
- jekyll-seo-tag
- jekyll-sitemap
exclude:
- ".sass-cache"
- ".netlify"
- vendor/
- Gemfile
- Gemfile.lock
- README.md
