---
title: Miguel Carvajal
description: Profesor de Periodismo y director del Máster en Innovación en Periodismo de la Universidad Miguel Hernández
url: https://miguelcarvajal.es
email: mcarvajal@umh.es
tagline: Profesor de Periodismo

future: true

author: Miguel Carvajal
twitter: 
  username: mcarvajal_
  card: summary_large_image
social:
  name: Miguel Carvajal
  links:
    - https://twitter.com/mcarvajal_
    - https://www.facebook.com/miguelcarvajal
    - https://github.com/miguelcarvajal

timezone: ES
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true

markdown: kramdown

include:
- _pages

permalink: notas/:year/:month/:day/:title:output_ext

# Compression
sass:
  sass_dir: _sass
  style: compressed

# Host
host: localhost

# Plugins 
plugins: [jekyll-paginate]
permalink:     pretty
paginate_path: 'page:num'
paginate: 10

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"