# Dependencies
markdown:         redcarpet
highlighter:      pygments

redcarpet:
    extensions: 
      - no_intra_emphasis
      - fenced_code_blocks
      - tables
      - strikethrough
      - superscript
      - autolink
      - hard_wrap
      - footnotes

# Permalinks
relative_permalinks: false

# Setup
title:            Miguel Carvajal
tagline:          'Profesor de Periodismo'
description:      'Profesor en la Universidad Miguel Hernández (UMH) y director del Máster en Innovación en Periodismo <a href="http://mip.umh.es" target="_blank">(MIP)</a>.'
url:              http://miguelcarvajal.es

author:
  name:           'Miguel Carvajal'
  url:            https://twitter.com/mcarvajal_

# Custom vars
version:          2.1.0

github:
  repo:           miguelcarvajal/miguelcarvajal.github.io
  branch:         master
theme: jekyll-theme-cayman