name: Update CSVs from Google Sheets

on:
  schedule:
    - cron: '0 0 * * *' # Cambia esta línea según la frecuencia deseada
  workflow_dispatch: # Permite ejecutar manualmente el workflow

jobs:
  update-csvs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install gspread pandas oauth2client

    - name: Download CSVs from Google Sheets
      env:
        GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
      run: |
        import json
        import gspread
        from oauth2client.service_account import ServiceAccountCredentials
        import pandas as pd
        import os

        # Autenticación con la API de Google Sheets
        scope = ["https://spreadsheets.google.com/feeds", "https://www.googleapis.com/auth/drive"]
        credentials = ServiceAccountCredentials.from_json_keyfile_dict(json.loads(os.environ["GCP_CREDENTIALS"]), scope)
        client = gspread.authorize(credentials)

        # ID de tu Google Sheet
        spreadsheet_id = '15sKk88cRmRlp3OWAeBYRwx31pCXjqpR60yeqlBFAduI'
        spreadsheet = client.open_by_key(spreadsheet_id)

        # Lista de nombres de las hojas
        sheet_names = ['articulos', 'art_no_index', 'libros', 'capitulos', 'proyectos', 'congresos', 'peer_review', 'comites', 'seminarios', 'estancias', 'docencia', 'metricas']

        # Carpeta donde se guardarán los CSVs
        output_folder = '_data'

        # Crear la carpeta si no existe
        if not os.path.exists(output_folder):
            os.makedirs(output_folder)

        # Descargar cada hoja como CSV
        for sheet_name in sheet_names:
            sheet = spreadsheet.worksheet(sheet_name)
            data = sheet.get_all_records()
            df = pd.DataFrame(data)
            df.to_csv(os.path.join(output_folder, f"{sheet_name}.csv"), index=False)

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add .
        git commit -m "Update CSVs from Google Sheets"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
